apiVersion: kafka.strimzi.io/v1alpha1
kind: Kafka
metadata: 
 name: my-cluster
spec:
 kafka:
   replicas: 5
   listeners:
     external:
       type: route
   storage:
     type: ephemeral
 zookeeper:
   replicas: 5
   storage:
     type: ephemeral
 entityOperator:
   topicOperator: {}
